### ISSUE TITLE
Support for Elasticsearch 1.4

### ISSUE THREAD

**Issue by elvarb** [spinscale/elasticsearch-graphite-plugin#12]
Where I have this plugin installed we are running Elasticsearch 1.3.4 but are planning to go to 1.4 soon.

**Comment by spinscale** [comment]
are you up for a PR? Would be awesome!

sorry for the late reply

**Comment by elvarb** [comment]
For a PR?

**Comment by rgardam** [comment]
I have sent a pull request.

**Comment by spinscale** [comment]
incorporated. thx for helping!
