### ISSUE TITLE
metrics.graphite.exclude regexp

### ISSUE THREAD

**Issue by mohierf** [spinscale/elasticsearch-graphite-plugin#15]
Any example on how to use this parameter should be appreciated ...

 I would like to filter the metrics associated to all the indexes in my ES. I then tried : 
```
metrics.graphite.prefix: knm.elasticsearch.ipmfrance
knm.elasticsearch.ipmfrance.[indexes|search].*
```
 to filter the indexes and search metrics but the service does not send any metric to Graphite.

 I also tried : 
```
metrics.graphite.exclude: knm.elasticsearch.ipmfrance.indexes.*
metrics.graphite.exclude: knm.elasticsearch.ipmfrance.search.*
```

 but no more success because I receive all the indexes metrics.

**Comment by spinscale** [comment]
it is a single configuration setting. 

I added an example test to make sure it is easier to understand, see [here](https://github.com/spinscale/elasticsearch-graphite-plugin/blob/master/src/test/java/org/elasticsearch/module/graphite/test/GraphitePluginIntegrationTest.java#L74-L90). Please open a new PR to add docs...

If there is something missing and it is actually a bug, please file a new issue
