### ISSUE TITLE
request to upload plugin to maven central

### ISSUE THREAD

**Issue by khrisrichardson** [spinscale/elasticsearch-graphite-plugin#5]
Hi, Alexander.

Any chance you could deploy the built artifact to maven central or sonatype? It appears that doing so would simplify the following instructions, since as is the case with your suggest plugin, it appears to be possible to download plugins from a maven repository as well as from github...

``` bash
git clone https://github.com/spinscale/elasticsearch-graphite-plugin
cd elasticsearch-graphite-plugin
mvn package
```

Cheers

**Comment by wizard124** [comment]
Was this ever moved to Maven Central?  I'm a noob and the instructions provided are confusing to me.  If anyone has any information that would help please let me know.

Thanks
